site_name: Docs page
site_dir: public
repo_url: http://localhost:8080/k8s-doc
theme:
    name: material
markdown_extensions:
    - admonition
nav:
    - Home: README.md
    - HowTo:
        - 'Kubernetes': 'howto/kubernetes/kubernetes-help.md'
        - Az:  
            - 'Az Commands': 'howto/az/az-help.md'